# Generated by Django 4.1.2 on 2022-12-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cust', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showings',
            name='sociallyDistanced',
            field=models.BooleanField(default=False),
        ),
    ]
